/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as OperatingHoursRouteImport } from './routes/operating-hours'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventDaysRouteImport } from './routes/event-days'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatingHoursRoute = OperatingHoursRouteImport.update({
  id: '/operating-hours',
  path: '/operating-hours',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventDaysRoute = EventDaysRouteImport.update({
  id: '/event-days',
  path: '/event-days',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/event-days': typeof EventDaysRoute
  '/login': typeof LoginRoute
  '/operating-hours': typeof OperatingHoursRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/event-days': typeof EventDaysRoute
  '/login': typeof LoginRoute
  '/operating-hours': typeof OperatingHoursRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/event-days': typeof EventDaysRoute
  '/login': typeof LoginRoute
  '/operating-hours': typeof OperatingHoursRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/event-days'
    | '/login'
    | '/operating-hours'
    | '/reservations'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/event-days'
    | '/login'
    | '/operating-hours'
    | '/reservations'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/event-days'
    | '/login'
    | '/operating-hours'
    | '/reservations'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EventDaysRoute: typeof EventDaysRoute
  LoginRoute: typeof LoginRoute
  OperatingHoursRoute: typeof OperatingHoursRoute
  ReservationsRoute: typeof ReservationsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operating-hours': {
      id: '/operating-hours'
      path: '/operating-hours'
      fullPath: '/operating-hours'
      preLoaderRoute: typeof OperatingHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-days': {
      id: '/event-days'
      path: '/event-days'
      fullPath: '/event-days'
      preLoaderRoute: typeof EventDaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EventDaysRoute: EventDaysRoute,
  LoginRoute: LoginRoute,
  OperatingHoursRoute: OperatingHoursRoute,
  ReservationsRoute: ReservationsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
